### ISSUE TITLE
проблема при импорте

### ISSUE THREAD

**Issue by eurweb** [Medniy2000/ua_locations#1]
при импорте командой

psql postgres -U postgres <  geo_digest_06_08_2021.sql

выдает ошибку **ERROR:  relation "public.osm_locations" does not exist**

![Screenshot from 2021-08-08 17-57-44](https://user-images.githubusercontent.com/11030366/128636448-72b80e4b-d672-438b-b137-3692e46b6545.png)

**Comment by Medniy2000** [comment]
Fixed!
@eurweb, please check.
